
DELETE FROM Book
DBCC CHECKIDENT ('Book', RESEED, 0);

INSERT INTO [dbo].[Book] ([Title], [Author], [Genre], [Room]) VALUES
(N'To Kill a Mockingbird', N'Harper Lee', N'Fiction', N'Living Room'),
(N'1984', N'George Orwell', N'Dystopian', N'Study'),
(N'The Great Gatsby', N'F. Scott Fitzgerald', N'Fiction', N'Bedroom'),
(N'Moby Dick', N'Herman Melville', N'Adventure', N'Basement'),
(N'Pride and Prejudice', N'Jane Austen', N'Romance', N'Living Room'),
(N'The Catcher in the Rye', N'J.D. Salinger', N'Coming-of-Age', N'Study'),
(N'War and Peace', N'Leo Tolstoy', N'Historical', N'Library'),
(N'Crime and Punishment', N'Fyodor Dostoevsky', N'Psychological', N'Study'),
(N'The Hobbit', N'J.R.R. Tolkien', N'Fantasy', N'Living Room'),
(N'The Lord of the Rings', N'J.R.R. Tolkien', N'Fantasy', N'Living Room'),
(N'Brave New World', N'Aldous Huxley', N'Dystopian', N'Study'),
(N'Jane Eyre', N'Charlotte Brontë', N'Romance', N'Bedroom'),
(N'Wuthering Heights', N'Emily Brontë', N'Romance', N'Bedroom'),
(N'The Odyssey', N'Homer', N'Classic', N'Study'),
(N'The Iliad', N'Homer', N'Classic', N'Study'),
(N'Dracula', N'Bram Stoker', N'Horror', N'Basement'),
(N'Frankenstein', N'Mary Shelley', N'Science Fiction', N'Study'),
(N'The Da Vinci Code', N'Dan Brown', N'Thriller', N'Living Room'),
(N'Angels & Demons', N'Dan Brown', N'Thriller', N'Living Room'),
(N'The Shining', N'Stephen King', N'Horror', N'Basement'),
(N'It', N'Stephen King', N'Horror', N'Basement'),
(N'Pet Sematary', N'Stephen King', N'Horror', N'Basement'),
(N'Misery', N'Stephen King', N'Thriller', N'Study'),
(N'Dune', N'Frank Herbert', N'Science Fiction', N'Study'),
(N'Foundation', N'Isaac Asimov', N'Science Fiction', N'Study'),
(N'I, Robot', N'Isaac Asimov', N'Science Fiction', N'Study'),
(N'The Martian', N'Andy Weir', N'Science Fiction', N'Living Room'),
(N'Ready Player One', N'Ernest Cline', N'Science Fiction', N'Bedroom'),
(N'Ender''s Game', N'Orson Scott Card', N'Science Fiction', N'Study'),
(N'The Alchemist', N'Paulo Coelho', N'Philosophical', N'Bedroom'),
(N'Norwegian Wood', N'Haruki Murakami', N'Fiction', N'Bedroom'),
(N'Kafka on the Shore', N'Haruki Murakami', N'Magical Realism', N'Study'),
(N'1Q84', N'Haruki Murakami', N'Science Fiction', N'Study'),
(N'A Game of Thrones', N'George R. R. Martin', N'Fantasy', N'Living Room'),
(N'A Clash of Kings', N'George R. R. Martin', N'Fantasy', N'Living Room'),
(N'A Storm of Swords', N'George R. R. Martin', N'Fantasy', N'Living Room'),
(N'The Name of the Wind', N'Patrick Rothfuss', N'Fantasy', N'Living Room'),
(N'The Wise Man''s Fear', N'Patrick Rothfuss', N'Fantasy', N'Living Room'),
(N'The Road', N'Cormac McCarthy', N'Post-apocalyptic', N'Basement'),
(N'The Sun Also Rises', N'Ernest Hemingway', N'Fiction', N'Study'),
(N'For Whom the Bell Tolls', N'Ernest Hemingway', N'War', N'Study'),
(N'The Old Man and the Sea', N'Ernest Hemingway', N'Fiction', N'Bedroom'),
(N'A Farewell to Arms', N'Ernest Hemingway', N'War', N'Study'),
(N'The Picture of Dorian Gray', N'Oscar Wilde', N'Philosophical', N'Bedroom'),
(N'The Scarlet Letter', N'Nathaniel Hawthorne', N'Classic', N'Study'),
(N'The Grapes of Wrath', N'John Steinbeck', N'Historical', N'Study'),
(N'Of Mice and Men', N'John Steinbeck', N'Fiction', N'Bedroom'),
(N'The Pearl', N'John Steinbeck', N'Allegory', N'Bedroom'),
(N'East of Eden', N'John Steinbeck', N'Fiction', N'Bedroom'),
(N'The Book Thief', N'Markus Zusak', N'Historical', N'Living Room'),
(N'The Fault in Our Stars', N'John Green', N'Romance', N'Bedroom'),
(N'Paper Towns', N'John Green', N'Young Adult', N'Bedroom'),
(N'Looking for Alaska', N'John Green', N'Coming-of-Age', N'Bedroom'),
(N'An Abundance of Katherines', N'John Green', N'Young Adult', N'Bedroom'),
(N'Divergent', N'Veronica Roth', N'Dystopian', N'Living Room'),
(N'Insurgent', N'Veronica Roth', N'Dystopian', N'Living Room'),
(N'Allegiant', N'Veronica Roth', N'Dystopian', N'Living Room'),
(N'The Maze Runner', N'James Dashner', N'Dystopian', N'Basement'),
(N'The Scorch Trials', N'James Dashner', N'Dystopian', N'Basement'),
(N'The Death Cure', N'James Dashner', N'Dystopian', N'Basement'),
(N'Carry On', N'Rainbow Rowell', N'Fantasy', N'Bedroom'),
(N'Circe', N'Madeline Miller', N'Mythology', N'Living Room'),
(N'The Song of Achilles', N'Madeline Miller', N'Mythology', N'Bedroom'),
(N'Atomic Habits', N'James Clear', N'Self-Help', N'Study'),
(N'The Power of Habit', N'Charles Duhigg', N'Self-Help', N'Study'),
(N'Outliers', N'Malcolm Gladwell', N'Non-Fiction', N'Study'),
(N'Talking to Strangers', N'Malcolm Gladwell', N'Non-Fiction', N'Study'),
(N'The Tipping Point', N'Malcolm Gladwell', N'Non-Fiction', N'Study'),
(N'Think and Grow Rich', N'Napoleon Hill', N'Personal Development', N'Study'),
(N'Rich Dad Poor Dad', N'Robert Kiyosaki', N'Finance', N'Study'),
(N'The Intelligent Investor', N'Benjamin Graham', N'Finance', N'Study'),
(N'A Brief History of Time', N'Stephen Hawking', N'Science', N'Study'),
(N'The Universe in a Nutshell', N'Stephen Hawking', N'Science', N'Study'),
(N'Cosmos', N'Carl Sagan', N'Science', N'Study'),
(N'Sapiens', N'Yuval Noah Harari', N'History', N'Study'),
(N'Homo Deus', N'Yuval Noah Harari', N'Future', N'Study'),
(N'21 Lessons for the 21st Century', N'Yuval Noah Harari', N'Current Affairs', N'Study'),
(N'Born a Crime', N'Trevor Noah', N'Autobiography', N'Living Room'),
(N'The Diary of a Young Girl', N'Anne Frank', N'Biography', N'Bedroom'),
(N'Steve Jobs', N'Walter Isaacson', N'Biography', N'Study'),
(N'Elon Musk', N'Ashlee Vance', N'Biography', N'Study'),
(N'The Wright Brothers', N'David McCullough', N'Biography', N'Study'),
(N'Leonardo da Vinci', N'Walter Isaacson', N'Biography', N'Study'),
(N'Quiet', N'Susan Cain', N'Psychology', N'Study'),
(N'Grit', N'Angela Duckworth', N'Psychology', N'Study'),
(N'Man''s Search for Meaning', N'Viktor Frankl', N'Psychology', N'Study'),
(N'The Art of War', N'Sun Tzu', N'Strategy', N'Study'),
(N'Meditions', N'Marcus Aurelius', N'Philosophy', N'Study'),
(N'The Prince', N'Machiavelli', N'Political Theory', N'Study'),
(N'The Republic', N'Plato', N'Philosophy', N'Study'),
(N'Beyond Good and Evil', N'Nietzsche', N'Philosophy', N'Study'),
(N'Tao Te Ching', N'Laozi', N'Philosophy', N'Study'),
(N'The Art of Happiness', N'Dalai Lama', N'Philosophy', N'Bedroom');
